### ISSUE TITLE
Renew Economic Event Database

### ISSUE THREAD

**Issue by fsanal** [fsanal/FinanceNewsApp#7]
Find an Economic Event Database with real economic events and corresponding date delimiters. Should be easy to find. Create a new table with this data.

**Comment by mkongsiri** [comment]
Added a handful of events from: http://timelinesdb.com/listevents.php?subjid=464&dayinhist=0&date1=-99999999999&date2=99999999999&words=&title=Economics&fromrec=1200

Note that such data was very hard to find and it seems that giving date delimiters is impossible. However, providing a year is feasible and the schema has been updated.
